POST http://localhost:5000/api/v1/admin/add-admin
Content-Type: application/json

{
    "name": "Munna",
    "email": "test@gmail.com",
    "password": "password"
}

###
POST http://localhost:5000/api/v1/admin/login-admin
Content-Type: application/json

{
    "name": "Munna",
    "email": "testUpdate@gmail.com",
    "password": "passwordUpdate"
}

###
PATCH  http://localhost:5000/api/v1/admin/update-admin
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RVcGRhdGVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU4MjQ1MTg5fQ.1nOYPbOs4X7Sdfq3kQU1-TiytQ2sEXGFRqDmgwCgl2g

{
    "name": "Munna Update two",
    "email": "testUpdatetwo@gmail.com",
    "password": "passwordUpdatetwo"
}

###
GET http://localhost:5000/api/v1/categories/get-categories

###
POST http://localhost:5000/api/v1/categories/add-category
Content-Type: application/json

{
    "name": "test three", 
    "description": "test description"
}

###
PATCH http://localhost:5000/api/v1/categories/update-category?id=62d8384a7f2da326003ad012
Content-Type: application/json

{
    "name": "new update category"
}



###
PATCH http://localhost:5000/api/v1/categories/delete-category?id=62da2493ac042c5a8143853b
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU4MjQzODA3fQ.ThfajumBjZJVb6FSd1FZxRncZitPJaDY8nQU4ux9lrk